- operators/combination/combinelatest.md
- operators/combination/concat.md
- operators/combination/merge.md
- operators/combination/startwith.md
- operators/combination/withlatestfrom.md
- operators/creation/from.md
- operators/creation/frompromise.md
- operators/creation/of.md
- operators/error_handling/catch.md
- operators/filtering/debounce.md
- operators/filtering/debouncetime.md
- operators/filtering/distinctuntilchanged.md
- operators/filtering/filter.md
- operators/filtering/take.md
- operators/filtering/takeuntil.md
- operators/multicasting/share.md
- operators/transformation/buffertime.md
- operators/transformation/concatmap.md
- operators/transformation/map.md
- operators/transformation/mergemap.md
- operators/transformation/scan.md
- operators/transformation/switchmap.md
- operators/utility/do.md
> Common Operator Description

- operators/filtering/first.md
This would significantly change the structure of each page.  A lot more work, and the explanation is very long and wordy.  But this way it is more clear and perhaps read easier.
> Format testing

- operators/filtering/distinctuntilchanged.md
> Grammar: change then to than

- operators/transformation/groupby.md
> removed unnecessary spread operator

- operators/filtering/filter.md
The was a space missing.
(I did not do a mass edit on all files. Just saw this while reading.)
> Fix markdown

- README.md
Hi @btroncone , I'm a RxJS fan and I like your learn-rxjs very much as its clear examples and detailed explanations. So I translate it to Chinese for more people to learn RxJS with lower learning curve.
So I hope to add a `Translations` link to your README. Thank you~
Best wishes!
> add Chinese localization link to the README

- operators/transformation/exhaustmap.md
Added a second example and fixed jsFiddle link in first example.
> New example

- operators/combination/forkjoin.md
Change 'When all observables complete emit the last value from each.' to 'When all observables complete, emit the last value from each.'
> Add comma for clarity

- SUMMARY.md
- operators/README.md
- operators/transformation/README.md
- operators/transformation/reduce.md
Related issue: 
https://github.com/btroncone/learn-rxjs/issues/39
> Added example for reduce

- operators/README.md
- operators/complete.md
Fixes a typo in the link to exhaustMap.
> Fixes link for exhaustMap

- operators/combination/forkjoin.md
> docs(forkJoin): updated explanations and examples

- operators/filtering/skip.md
Added a why use section for skip and an example comparing it to a specific filter use case.
> Why Use Section

- operators/creation/fromevent.md
- operators/transformation/buffercount.md
- operators/transformation/switchmap.md
- operators/utility/do.md
- recipes/README.md
- recipes/progressbar.md
Add progress bar recipe.
@barryrowe @yuHLe
> Progress bar recipe

- SUMMARY.md
- recipes/README.md
- recipes/gameloop.md
Adds a new recipe for a small Game Loop. 
Attempted to update all the navigation points, but may have missed some.
Input on the description blurb is also welcome.
> Add Game Loop recipe

- operators/creation/fromevent.md
- operators/creation/frompromise.md
- operators/creation/timer.md
- operators/transformation/map.md
- operators/transformation/switchmap.md
- recipes/README.md
- recipes/http-polling.md
This is the initial setup for a basic HTTP Polling Recipe.
> Add new recipe for HTTP Polling

- operators/creation/from.md
- operators/creation/frompromise.md
- operators/filtering/filter.md
- operators/transformation/mapto.md
- operators/transformation/mergemap.md
- recipes/http-polling.md
Update to polling example.
CC: @Barryrowe @yuHLe for review
> refactor(http-polling): update http polling example

- operators/error_handling/retry.md
- operators/filtering/sample.md
- operators/filtering/single.md
- operators/filtering/skip.md
- operators/filtering/take.md
- operators/filtering/takeuntil.md
- operators/filtering/takewhile.md
- operators/filtering/throttletime.md
some imports were missing the from
> fix broken import statements

- operators/combination/forkjoin.md
> Missed ','

- operators/error_handling/catch.md
was `import { of } from 'rxjs/observable/of';`
> documentation: of is imported from rxjs

- operators/utility/finalize.md
Included a simple example of the finalize operator
> Include finalize example

- operators/filtering/audittime.md
> Included example and description for auditTime

- README.md
links are not working from main page and this is annoying ;)
Thanks for gathering all that!
> Fixing recipes link in Readme

- operators/error_handling/retrywhen.md
The comments in the example states that it will restart in 5 seconds, but this is not true since the val received by the delayWhen operator will be the invalid 6 value. Thus it will restart in 6 seconds.
> Corrected delayWhen example

- SUMMARY.md
> Update SUMMARY.md - Fix camel case error

- README.md
- SUMMARY.md
- operators/creation/fromevent.md
- operators/creation/interval.md
- operators/filtering/takewhile.md
- operators/transformation/map.md
- operators/transformation/scan.md
- operators/transformation/switchmap.md
- operators/utility/do.md
- recipes/README.md
- recipes/catch-the-dot-game.md
This one is a little bit unusual :)
> Added Catch The Dot Game recipe

- README.md
- SUMMARY.md
- operators/combination/startwith.md
- operators/combination/withlatestfrom.md
- operators/creation/fromevent.md
- operators/creation/interval.md
- operators/filtering/takeuntil.md
- operators/transformation/map.md
- operators/transformation/scan.md
- operators/utility/do.md
- operators/utility/repeat.md
- recipes/space-invaders-game.md
This one uses mostly functional programming/state management inside scan but RxJs drives it all so maybe it's good for LearnRxJs too :)
> Added space invaders recipe

- README.md
- SUMMARY.md
- operators/combination/combinelatest.md
- operators/combination/startwith.md
- operators/creation/fromevent.md
- operators/creation/interval.md
- operators/filtering/takewhile.md
- operators/transformation/map.md
- operators/transformation/scan.md
- operators/transformation/switchmap.md
- recipes/README.md
- recipes/alphabet-invasion-game.md
- subjects/behaviorsubject.md
> Added Alphabet Invasion Game recipe

- recipes/alphabet-invasion-game.md
Wanted to get it out so fast that I forgot about TS interfaces :)
> Added TS interfaces to Alphabet Invasion Game

- SUMMARY.md
- operators/README.md
- operators/complete.md
- operators/creation/README.md
- operators/creation/ajax.md
https://github.com/btroncone/learn-rxjs/issues/175
Let me know your thoughts and how I could improve this :) @btroncone
> Adds ajax operator

- README.md
- SUMMARY.md
- concepts/README.md
- concepts/rxjs-primer.md
I have been working on a firehose type introductory article to introduce the main concepts of RxJS to new users. 
If you get a chance to review over the next week, would you be able to leave any comments, suggestions, or ideas? Thanks in advance!
@adamlubek @Barryrowe @yuHLe
> RxJS primer

- operators/creation/of.md
> Fix misspelling. Method 'of'

- subjects/behaviorsubject.md
Links to the "Alphabet Invasion Game" and "Car Racing Game" are broken,
> Update  behaviorsubject.md page to fix broken link

- operators/creation/defer.md
> Update defer.md to fix broken link

- operators/creation/empty.md
The "save indicator" recipe link is broken
> Fix empty.md to fix broken link

- concepts/rxjs-primer.md
Replace Merge by Concat in the paragraphe about Concat based operator
> Fix a wrong reference to operator

- operators/error_handling/retrywhen.md
_throw has been replaced by throwError
> chore(operators): fix import in retryWhen recipe

- subjects/subject.md
I have proposed this change to make it more clear for new RxJS learners. If accepted, please update Stackblitz with the same.
The console log will show the process more clear than before.
> Making the example more clear

- operators/utility/do.md
> docs(do): source code link changed to tap from do
