operators/transformation/scan.md
In the example section of the scan operator, there are too many `### Example` title, so I uniform the format as other operators.
=> uniform the format for the scan operator

SUMMARY.md, concepts/README.md, concepts/operator-imports.md
Explanation for importing and using operators when creating public libraries. Waiting on future RxJS release to publish.
=> Operator import explanation

SUMMARY.md
Link to cache in the multicasting section doesn't point anywhere.
=> Removed link to cache from summary

SUMMARY.md, operators/utility/README.md
Just noticed a couple of things when reading through the docs, this PR fixes the following:
- Missing `exhaustMap` link to the summary
- A couple of utility operator (`materialize` + `observeOn`) links that don't exist
=> Update summary and utility operators

README.md
Add link to [reactive.how](http://reactive.how) in the Tools section of the README.
Series of animated visualization of Rx operators, in the form of cards. For example:
<a href="http://reactive.how"><img width="584" alt="capture d ecran 2017-11-03 a 10 53 45" src="https://user-images.githubusercontent.com/802010/32368233-62efa63c-c085-11e7-8dca-8f5224d7faa4.png"></a>
=> Add link to Reactive.how

operators/transformation/switchmap.md
Iterating on new sections to make operator sections more robust. The first is a `why`, trying to differentiate the point of use this operator over others when there is ambiguity.
Also considering adding a code walkthrough to the end of each page, may hold off to focus more on high quality examples that can be referenced in the initial breakdown.
Thoughts?
=> docs(operators): add explanation for switchMap

operators/filtering/takewhile.md
Was logging 3 instead of val.  Same output, but we didn't actually filter.
I could only update jsFiddle though (proxy).  Also the two links aren't tied to your accounts.  Not sure if you want to add them to add them.
=> Fixed console.log mistake in example 2

operators/combination/withlatestfrom.md
In the first example a second .pipe() was used against the withLatestFrom() result which doesn't compile. I don't think the nested pipe is needed here. In the second example the comma after withLatestFrom() was missing.
=> Fixed withLatestFrom example source

operators/utility/do.md
This PR fixes the link to `ReactiveX/rxjs do.ts`.
=> Fix link to ReactiveX/rxjs do.ts

operators/complete.md
I found this when I sync and translate the new content from the upstream.
=> fix the name of shareReplay in the complete list

operators/README.md
The [Operators](https://www.learnrxjs.io/operators/) page does not show the star for the `delay` operator, while the [Utility](https://www.learnrxjs.io/operators/utility/) does. Made the two pages consistent.
=> Add commonly used star for delay operator

operators/multicasting/sharereplay.md
By default shareReplay() will buff and replay all values not just the last one. We need to set the size to 1 to only keep last value.
=> shareReplay doesn't default to last value

operators/filtering/throttle.md
Unlike debouncing, throttling emits an initial value, *then* the suppression of notification kicks in.
=> Correct description of throttling

concepts/rxjs5-6.md
The document has been updated. This fixes the link so users don't have to click through two "redirects"
=> Update migrated document

operators/utility/topromise.md
I found the deprecation notice on `toPromise` to be very confusing, since no alternative is provided. I did some looking and couldn't find any evidence that it's been deprecated.
The short-lived pipable `toPromise` _was_ deprecated soon after it was made, but the one on the observable prototype lives on (which is what was documented on this page anyway).
[toPromise still exists in the RxJS codebase without any deprecation notice](https://github.com/ReactiveX/rxjs/blob/master/src/internal/Observable.ts#L346), and it is not mentioned in the [migration guide](https://github.com/ReactiveX/rxjs/blob/master/docs_app/content/guide/v6/migration.md#deprecations).
(The code samples should probably be updated too, but I want to narrow the scope of this PR.)
=> Remove deprecation notice on .toPromise()

operators/filtering/throttletime.md
Type Head is written as it's in the related recipes of `throttleTime` while it's not
=> Disconnect Type Head from throttleTime

operators/combination/forkjoin.md
I think the current example is incorrect because it doesn't use forkJoin operator.
=> Fix forkJoin example on StackBlitz.

README.md
Checking the links section I found that https://egghead.io/lessons/rxjs-introduction-to-rxjs-marble-testing isn't free anymore.
This PR marks this video with 💵 sign similar to "Introduction to Reactive Programming" above.
=> Mark Marble Testing video as not free

recipes/lockscreen.md
This PR removes unintentional 'and' suffix to 'touched' in `// as we swipe, we mark pads as touched and display selected numbers` comment.
=> Correct spelling error

subjects/subject.md
Link to the 'lockscreen' example is broken, you get a 404 error when trying to reach it from the Subject page.
=> Update Subject page to fix broken example link

concepts/rxjs-primer.md
`take` explanation used '`x`' for explaining taking `n` values then just afterward `takeLast` used 'n'.
I choose a middle ground with `n` because n is often associated with Int, and the use of ``(backtick) allow for a more readable sentence in my opinion.
Other options would have been:
- `x` for both sentences
- x for both sentences
- n for both sentences
- completely another way to convey the meaning, so long as it is consistant.
=> Coherent variable for constant numeric value

operators/utility/do.md
the `'` at the start of the link was breaking the rendering on GitBook (https://www.learnrxjs.io/learn-rxjs/operators/utility/do)
Looks like the `'` is in the recipe list of other operators pages as well, but I'm just doing a quick edit through the web interface. Can't stop for this right now.
=> docs(do): "save indicator" broken link on gitbook

concepts/rxjs-primer.md
Hi, the link for catchError on the rxjs site doesn't work. 
I tried to fix it by looking how you link to other stuff. If that wasn't correct, please disregard
=> Fixed link to error handling

operators/combination/concatall.md
In third example there was a wrong import path.
=> Fix concatAll code example

operators/creation/fromevent.md
It's a minor typo and you can't see it in the page rendered on GitHub, but GitBook seems to not understand a link with unclosed quote.
=> Fix broken link

operators/utility/topromise.md
Using `<div class="ua-ad"> ... </div>` causes the markdown image not to render properly.
=> fix(operators): fix broken image

operators/conditional/iif.md
The link to the official docs was outdated  and pointed to a 404 page on rxjs.dev.
=> fix(iif.md): update the link to the official docs
